version: "3.8"
services:
  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - art
  api:
    container_name: api
    build: .
    environment:
      - PORT=8080
      - MONGO_DATABASE=store
      - MONGO_COLLECTION=storecollection
      - MONGO_URI=mongodb://mongodb:27017
    ports:
      - "8080:8080"
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - mongodb
    networks:
      - art

volumes:
  api:
  mongodb-data:

networks:
  art:
    driver: bridge
